version: '3.8'

services:
  api:
    build:
      context: ./
    ports:
    - ${APPLICATION_PORT}:${APPLICATION_PORT}
    volumes:
      - ./:/app
    depends_on:
      - migrations
    environment:
      - APPLICATION_MODE=${APPLICATION_MODE}
      - APPLICATION_PORT=${APPLICATION_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  migrations:
    build: ./migrations
    command: make
    depends_on:
      - postgres
    environment:
      - GOOSE_DRIVER=${GOOSE_DRIVER}
      - GOOSE_DBSTRING=postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}&sslmode=disable

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
