# syntax=docker/dockerfile:1

FROM golang

WORKDIR /app

RUN go install github.com/githubnemo/CompileDaemon@latest
COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE ${APPLICATION_PORT}

# Run
CMD ["make", "run_local"]
