FROM golang

WORKDIR /app

RUN go install github.com/githubnemo/CompileDaemon@latest
COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE ${APPLICATION_PORT}

# Run
CMD CompileDaemon \
  -build="go build -o ./bin/api ./cmd/api/main.go" \
  -command="./bin/api" \
  -exclude-dir=".git" \
  -color \
  -log-prefix=false
