FROM golang:alpine AS builder

RUN apk update && apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN GOOS=linux GOARCH=amd64 \
  go build \
  -ldflags="-w -s -X main.buildHash=${COMMIT} -X main.buildTime=${BUILD_TIME}" \
  -o /go/bin/api \
  ./cmd/api/main.go

FROM scratch

COPY --from=builder /go/bin/api /go/bin/api

EXPOSE ${APPLICATION_PORT}

ENTRYPOINT ["/go/bin/api"]
