basePath: /
definitions:
  file_info.FileInfo:
    properties:
      filename:
        type: string
      id:
        type: integer
      status:
        $ref: '#/definitions/file_info.FileInfoStatus'
      timestamp:
        type: string
    type: object
  file_info.FileInfoStatus:
    enum:
    - recieved
    - in_queue
    - processing
    - done
    - error
    type: string
    x-enum-varnames:
    - StatusRecieved
    - StatusInQueue
    - StatusProcessing
    - StatusDone
    - StatusError
  file_info.HttpResponseErr:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
  description: API for file processing
  title: File processing API
  version: "1.0"
paths:
  /files/{name}:
    get:
      description: get file info by its name
      parameters:
      - description: File name
        in: path
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/file_info.FileInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/file_info.HttpResponseErr'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/file_info.HttpResponseErr'
        "408":
          description: Request Timeout
          schema:
            $ref: '#/definitions/file_info.HttpResponseErr'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/file_info.HttpResponseErr'
      summary: Get meta information about a file
      tags:
      - files
swagger: "2.0"
